[project]
name = "pile-supernote"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.10.9",
    "docopt>=0.6.2",
    "loguru>=0.7.2",
]
